EEG_MIN_AMPLITUDE = -2000
EEG_MAX_AMPLITUDE = 2000

EEG_FLAT_STD_THRESHOLD = 1e-6

EEG_CLIPPING_THRESHOLD = 0.99

ET_VALID_MIN_X = -1.0
ET_VALID_MAX_X = 2.0

ET_VALID_MIN_Y = -1.0
ET_VALID_MAX_Y = 2.0

ET_NAN_WARNING_RATIO = 0.10

TIMESTAMP_GAP_WARNING_SEC = 0.5

SUBJECT_MIN_DURATION_SEC = 300
